channels:
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- asttokens=2.4.1
- bzip2=1.0.8
- ca-certificates=2023.11.17
- ipykernel=6.29.0
- ipython=8.20.0
- jedi=0.19.1
- jupyter_core=5.7.1

- pip:
  - decord==0.6.0
  - lightning==2.0.6
  - huggingface-hub==0.23.0
  - imageio==2.31.1
  - pandas==2.1.4
  - plotly==5.18.0
  - scipy==1.11.2
  - librosa==0.9.2
  - opencv-python-headless==4.8.0.76
  - wandb
  - nbformat==5.9.2
  - transformers==4.35.2
  - ffmpeg-python==0.2.0



name: pytorch_env_1mdf
